---
oauth:
    consumer_key: 'PUT_YOUR_OAUTH_CONSUMER_KEY_HERE'
    consumer_secret: 'PUT_YOUR_OAUTH_SECRET_KEY_HERE'
    access_token_key: 'PUT_YOUR_OAUTH_TOKEN_KEY_HERE'
    access_token_secret: 'PUT_YOUR_OAUTH_TOKEN_SECRET_HERE'
...
